<a href="https://colab.research.google.com/github/zubaeteee20210205109-droid/Trial/blob/main/numpy_sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a= np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [ ]:
b= np.array([[6.0,5,2,1],[3,4.0,8,9]])
print(b)

[[6. 5. 2. 1.]
 [3. 4. 8. 9.]]


In [ ]:
# dimension
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
# shape
a.shape

(3,)

In [ ]:
b.shape

(2, 4)

In [ ]:
# type
a.dtype

dtype('int16')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
#size (dtype = int 16, size = 2 / if 32 then size= 4)
a.itemsize

2

In [ ]:
b.itemsize

8

In [ ]:
# total size
a.size * a.itemsize

6

In [ ]:
b.nbytes

64

In [ ]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# get specific element [r,c]
A[1,5]

np.int64(13)

In [ ]:
#specific row
A[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
#specific column
A[:, 5]

array([ 6, 13])

In [ ]:
#getting a little more fancy [startindex:endindex:stepsize]
A[0,1:6:1]

array([2, 3, 4, 5, 6])

In [ ]:
A[1,5] = 20
print(A)

A[:,2]= 5
print(A)

A[:,2]= [1,2]
print(A)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
B= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(B)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#get specific element
B[0,1,1]


np.int64(4)

In [ ]:
B[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
# replace
B[:, 1, :] = [[9,9],[8,8]]
print(B)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#All 1s matrix
np.ones((4,2,3),dtype = 'int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [ ]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
#any other number (full_light)
np.full_like(A.shape,4)

array([4, 4])

In [ ]:
np.full_like(A,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#random decimal number
np.random.rand(2,3)

array([[0.74182408, 0.63277298, 0.43143167],
       [0.17737336, 0.90615833, 0.57020334]])

In [ ]:
#random integer value
np.random.randint(4,8,size=(3,3))


array([[5, 5, 5],
       [5, 5, 5],
       [5, 7, 4]])

In [ ]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#repeat an array
arr = np. array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [ ]:
#repeat an array
arr = np. array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
Output= np.ones((5,5))
print(Output)

Z= np.zeros((3,3))
Z[1,1]=9
print(Z)

Output[1:4,1:4]=Z
print(Output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#coppying array
a = np.array([1,2,3])
b=a.copy()
b[0]=10
print(a)
print(b)

[1 2 3]
[10  2  3]


In [ ]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a-2

array([-1,  0,  1,  2])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a+=2
a

array([ 7,  8,  9, 10])

In [ ]:
b= np.array([1,0,1,0])
a+b

array([ 8,  8, 10, 10])

In [ ]:
a**2

array([ 49,  64,  81, 100])

In [ ]:
#take the sin
np.sin(a)

array([ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [ ]:
a= np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#find the determinant
c= np.identity(3)
np.linalg.det(c)


np.float64(1.0)

In [ ]:
stats= np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats, axis=1)

array([1, 4])

In [ ]:
np.max(stats, axis= 1)

array([3, 6])

In [ ]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#vertically stacking vectors
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#horizontal stack
h1= np.ones((2,4))
h2= np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving data.txt to data.txt
Saving NumPy Tutorial.ipynb to NumPy Tutorial.ipynb


In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [ ]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
##you can index with a list in Numpy
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [ ]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [ ]:
((filedata> 50) & (filedata <100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
(~((filedata> 50) & (filedata <100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])